apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed
  name: backend-feed
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-feed
spec:
  ports:
  - name: http 
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: backend-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}